# Generated by Django 2.2 on 2019-05-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cola1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('diagonals', models.CharField(max_length=100)),
                ('sides', models.CharField(max_length=100)),
                ('positions', models.CharField(max_length=100)),
                ('positions_y', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ColaFridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('diagonals', models.CharField(max_length=100)),
                ('sides', models.CharField(max_length=100)),
                ('positions', models.CharField(max_length=100)),
                ('positions_y', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ColaRedShelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('diagonals', models.CharField(max_length=100)),
                ('sides', models.CharField(max_length=100)),
                ('positions', models.CharField(max_length=100)),
                ('positions_y', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('diagonals', models.CharField(max_length=100)),
                ('sides', models.CharField(max_length=100)),
                ('positions', models.CharField(max_length=100)),
                ('positions_y', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
