# Generated by Django 2.2 on 2019-05-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_colafridgeimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassFridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('diagonals', models.CharField(max_length=100)),
                ('sides', models.CharField(max_length=100)),
                ('positions', models.CharField(max_length=100)),
                ('positions_y', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
