# Generated by Django 2.2 on 2019-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_glassfridge'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlassFridgeImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_mean', models.CharField(max_length=100)),
                ('green_mean', models.CharField(max_length=100)),
                ('blue_mean', models.CharField(max_length=100)),
                ('overall_mean', models.CharField(max_length=100)),
                ('red_stand', models.CharField(max_length=100)),
                ('green_stand', models.CharField(max_length=100)),
                ('blue_stand', models.CharField(max_length=100)),
                ('overall_stand', models.CharField(max_length=100)),
            ],
        ),
    ]
